// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace AppModuleScssNamespace {
  export interface IAppModuleScss {
    bar1: string;
    bar2: string;
    hidden: string;
    left: string;
    loginButton: string;
    mobileNav: string;
    navItem: string;
    navbar: string;
    navbarWrapper: string;
    open: string;
    rainbow: string;
    right: string;
    toggleIcon: string;
  }
}

declare const AppModuleScssModule: AppModuleScssNamespace.IAppModuleScss;

export = AppModuleScssModule;
