// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace EventsModuleScssNamespace {
  export interface IEventsModuleScss {
    card: string;
    cardBody: string;
    cardContainer: string;
    cardDate: string;
    cardDay: string;
    cardFooter: string;
    cardHeader: string;
    eventLocation: string;
    eventTime: string;
    eventTitle: string;
    eventsContainer: string;
    footerIcon: string;
  }
}

declare const EventsModuleScssModule: EventsModuleScssNamespace.IEventsModuleScss;

export = EventsModuleScssModule;
