// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace EventsModuleScssNamespace {
  export interface IEventsModuleScss {
    ai: string;
    card: string;
    cardBody: string;
    cardContainer: string;
    cardDate: string;
    cardDay: string;
    cardFooter: string;
    cardHeader: string;
    cyber: string;
    eventLocation: string;
    eventTime: string;
    eventTitle: string;
    eventsContainer: string;
    footerIcon: string;
    general: string;
    hack: string;
    innovate: string;
  }
}

declare const EventsModuleScssModule: EventsModuleScssNamespace.IEventsModuleScss;

export = EventsModuleScssModule;
