// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace CommunityDescriptionModuleScssNamespace {
  export interface ICommunityDescriptionModuleScss {
    blob: string;
    communityCard: string;
    communityLinks: string;
    content: string;
    descHolder: string;
    header: string;
    logo: string;
  }
}

declare const CommunityDescriptionModuleScssModule: CommunityDescriptionModuleScssNamespace.ICommunityDescriptionModuleScss;

export = CommunityDescriptionModuleScssModule;
