// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace CommunityNavbarModuleScssNamespace {
  export interface ICommunityNavbarModuleScss {
    active: string;
    communities: string;
    hero: string;
    navigator: string;
    toggle: string;
  }
}

declare const CommunityNavbarModuleScssModule: CommunityNavbarModuleScssNamespace.ICommunityNavbarModuleScss;

export = CommunityNavbarModuleScssModule;
