// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace CommunityImagesModuleScssNamespace {
  export interface ICommunityImagesModuleScss {
    imageGrid: string;
    nextImageHolder: string;
    pic1: string;
    pic2: string;
    pic3: string;
    pic4: string;
  }
}

declare const CommunityImagesModuleScssModule: CommunityImagesModuleScssNamespace.ICommunityImagesModuleScss;

export = CommunityImagesModuleScssModule;
