// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace SuborgsModuleScssNamespace {
  export interface ISuborgsModuleScss {
    blue: string;
    communityLinks: string;
    content: string;
    fullName: string;
    glowOnHover: string;
    grey: string;
    header: string;
    logo: string;
    logoCard: string;
    orange: string;
    outreachGreen: string;
    pink: string;
    purple: string;
    red: string;
    sectionNav: string;
    spacer80px: string;
    subOrgNav: string;
    title: string;
    turquoise: string;
    yellow: string;
  }
}

declare const SuborgsModuleScssModule: SuborgsModuleScssNamespace.ISuborgsModuleScss;

export = SuborgsModuleScssModule;
