// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace StylesModuleScssNamespace {
  export interface IStylesModuleScss {
    active: string;
    ai: string;
    cyber: string;
    design: string;
    filterButtons: string;
    general: string;
    grid: string;
    gridFilters: string;
    gridWrapper: string;
    hack: string;
  }
}

declare const StylesModuleScssModule: StylesModuleScssNamespace.IStylesModuleScss;

export = StylesModuleScssModule;
