// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace EventsModuleScssNamespace {
  export interface IEventsModuleScss {
    active: string;
    ai: string;
    cardContainer: string;
    cyber: string;
    design: string;
    eventsContainer: string;
    filterButton: string;
    filterContainer: string;
    general: string;
    hack: string;
    header: string;
    headerText: string;
    mobileFilters: string;
    noEvents: string;
  }
}

declare const EventsModuleScssModule: EventsModuleScssNamespace.IEventsModuleScss;

export = EventsModuleScssModule;
