// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace CalendarModalModuleScssNamespace {
  export interface ICalendarModalModuleScss {
    modal: string;
    "modal-main": string;
    options: string;
  }
}

declare const CalendarModalModuleScssModule: CalendarModalModuleScssNamespace.ICalendarModalModuleScss;

export = CalendarModalModuleScssModule;
