// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace EventModuleScssNamespace {
  export interface IEventModuleScss {
    ai: string;
    backButton: string;
    container: string;
    coverContainer: string;
    cyber: string;
    date: string;
    eventBody: string;
    eventCover: string;
    eventDate: string;
    eventDay: string;
    eventDescription: string;
    eventHeader: string;
    eventInfo: string;
    eventLink: string;
    eventLinks: string;
    eventType: string;
    general: string;
    hack: string;
    innovate: string;
    location: string;
    time: string;
    title: string;
    titleLocationGrid: string;
  }
}

declare const EventModuleScssModule: EventModuleScssNamespace.IEventModuleScss;

export = EventModuleScssModule;
