const MOBILE_SM = 320;
const MOBILE_MD = 375;
const MOBILE_LG = 425;
const DESKTOP_SM = 768;
const DESKTOP_MD = 1024;
const DESKTOP_LG = 1440;

export { MOBILE_SM, MOBILE_MD, MOBILE_LG, DESKTOP_SM, DESKTOP_MD, DESKTOP_LG };
