// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace EventCardModuleScssNamespace {
  export interface IEventCardModuleScss {
    ai: string;
    card: string;
    cardBody: string;
    cardDate: string;
    cardDay: string;
    cardFooter: string;
    cardHeader: string;
    cyber: string;
    eventLocation: string;
    eventTime: string;
    eventTitle: string;
    general: string;
  }
}

declare const EventCardModuleScssModule: EventCardModuleScssNamespace.IEventCardModuleScss;

export = EventCardModuleScssModule;
