// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace QuestionModalModuleScssNamespace {
  export interface IQuestionModalModuleScss {
    "display-block": string;
    "display-none": string;
    modal: string;
    "modal-main": string;
    options: string;
  }
}

declare const QuestionModalModuleScssModule: QuestionModalModuleScssNamespace.IQuestionModalModuleScss;

export = QuestionModalModuleScssModule;
