// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace NavbarModuleScssNamespace {
  export interface INavbarModuleScss {
    bar1: string;
    bar2: string;
    hidden: string;
    left: string;
    loginButton: string;
    mobileNav: string;
    navItem: string;
    navbar: string;
    navbarWrapper: string;
    open: string;
    rainbow: string;
    right: string;
    toggleIcon: string;
  }
}

declare const NavbarModuleScssModule: NavbarModuleScssNamespace.INavbarModuleScss;

export = NavbarModuleScssModule;
